name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubunto-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install npm dependencies, cache them corretly
      # and run all Cypress tests

      - name: Cypress run
        uses: cypress-io/github-action@v5
        # after the test run completes stores videos and any screenhots

      - uses: actions/upload-artifact@v3
        # add the line below to store screenshots only on failures
        # if: failure()

        with:
          name: cypress-screenhots
          path: cypress/screenhots
          if-no-files-found: ignore
      - uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore
