name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubunto-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install npm dependencies, cache them corretly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5