name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Install and Start
        run: npm install && npm run test


      - name: Cypress run
        uses: cypress-io/github-action@v6

      # Store videos and screenshots after test run completes
      - name: Upload Cypress Screenshots
        uses: actions/upload-artifact@v3
        if: failure() # Store screenshots only on failures
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore

      - name: Upload Cypress Videos
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore
